package com.erp.domain.security;

/**
 * Application-wide permission modules (HR, inventory, finance, etc.).
 * Stored as STRING in JPA; DB enum values match these constant names.
 */
public enum AppModule {
    EMPLOYEE_PROFILE,
    CURRENT_JOB,
    SALARY,
    PAYROLL,
    LEAVES,
    LOANS,
    DEPENDENTS,
    APPRAISAL,
    IMMIGRATION,
    HR_REPORTS,
    HR_SETTINGS,
    HR_DASHBOARD,

    // ── HR Settings — per-tab permissions (HR_SETTINGS is the umbrella that grants all) ──
    HRS_ORG_STRUCTURE,
    HRS_DEPARTMENTS,
    HRS_JOB_CODES,
    HRS_ROLES,
    HRS_CONFIRMATIONS,
    HRS_CONTRACT_RENEWALS,
    HRS_APPRAISAL_CONFIG,
    HRS_LEAVE_TYPES,
    HRS_LEAVE_APPROVALS,
    HRS_LOAN_APPROVALS,
    HRS_POLICIES,
    HRS_SOCIAL,
    HRS_PERMISSIONS,

    // ── HR Reports — per-tab permissions (HR_REPORTS is the umbrella that grants all) ──
    HRR_WORKFORCE,
    HRR_PERFORMANCE,
    HRR_TIMESHEETS,
    HRR_ATTENDANCE_HISTORY,
    HRR_LEAVE_HISTORY,
    HRR_LOAN_HISTORY,
    HRR_IMMIGRATION_EXPIRY,
    HRR_PAYROLL_SUMMARY,
    HRR_EXIT_INTERVIEWS,
    HRR_ARCHIVE,
    HRR_HISTORY,

    INVENTORY_CATEGORY,
    INVENTORY_WAREHOUSE,
    INVENTORY_STOCK,
    INVENTORY_ITEM,
    INVENTORY_PURCHASE,
    INVENTORY_RECEIPT,
    INVENTORY_SALES,
    INVENTORY_DASHBOARD,
    FINANCE_COA,
    FINANCE_JOURNAL,
    FINANCE_LEDGER,
    FINANCE_INVOICE,
    FINANCE_PAYMENT,
    FINANCE_BUDGET,
    FINANCE_RECONCILIATION,
    FINANCE_REPORTS,
    FINANCE_DASHBOARD
}
