spring:
  profiles:
    active: mysql
  data:
    web:
      pageable:
        default-page-size: 20
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  config:
    import: optional:file:.env[.properties]

app:
  public-base-url: ${APP_PUBLIC_BASE_URL:http://localhost:5173}
  jwt:
    secret: "change-this-in-prod-32-bytes-minimum-secret-key-123456"
    issuer: "hrmodule"
    access-token-minutes: 60
    refresh-token-days: 7
  cors:
    allowed-origins: "http://localhost:5173,http://localhost:3001,http://localhost:3000,https://api.picominds.com,https://sunway-erp.vercel.app"
server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: DEBUG
    org.springframework.data.jpa: DEBUG
    org.hibernate.SQL: INFO

springdoc:
  override-server-url: true

azure:
  storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
    public-container: erp-public
    private-container: erp-private

