spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:hrdb}?createDatabaseIfNotExist=true&useSSL=${DB_SSL:false}&requireSSL=${DB_SSL:false}&verifyServerCertificate=${DB_VERIFY:false}&serverTimezone=UTC${DB_SSL_CA:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:hruser}
    password: ${DB_PASS:hrpass}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
