package com.erp.service.hr;

import com.erp.domain.hr.Company;
import com.erp.domain.hr.CompanyInvoiceSettings;

public final class InvoiceSettingsDefaults {
    public static final String HEADER_SUBTITLE = "Invoice generated by ERP system";
    public static final String NOTES_UNPAID =
            "{{companyName}} issued this invoice on {{invoiceDate}}. Payment is due on {{dueDate}}. "
                    + "Please use the bank details shown above and include reference {{invoiceId}} while paying. "
                    + "For account queries, contact your billing support team.";
    public static final String NOTES_PAID =
            "{{companyName}} confirms receipt of payment for reference {{invoiceId}} on {{paidDate}}. "
                    + "Thank you for your payment.";
    public static final String TERMS = String.join("\n",
            "Payment is due within 30 days of the invoice date. Late payments may incur a 2% monthly interest charge on the outstanding balance.",
            "All payments must be made in the company-configured currency to the bank account specified above. International wire transfer fees are the responsibility of the client.",
            "Services, licenses, hosting, and support are provided on a subscription basis. Non-payment will result in automatic suspension of services after 14 days past the due date.",
            "Any disputes regarding this invoice must be raised in writing within 7 business days of receipt. Silence will be deemed as acceptance of all charges.",
            "This invoice is subject to local taxation laws. Any future tax changes will be applied as per government regulations.",
            "Hosting and support services include a 99.9% uptime guarantee. Credits for downtime exceeding this threshold must be claimed within 30 days.",
            "All intellectual property rights for custom development work transfer to the client upon full payment of this invoice.");
    public static final String FOOTER_SIGNATURE =
            "This is a computer-generated document and does not require a physical signature.";

    private InvoiceSettingsDefaults() {
    }

    public static CompanyInvoiceSettings buildDefaults(Company company) {
        String companyLine = company.getCompanyName() + " | Commercial Registration: "
                + (company.getCrNo() == null ? "N/A" : company.getCrNo());
        String taxLine = "Tax ID: " + (company.getCompanyCode() == null ? "N/A" : company.getCompanyCode());

        return CompanyInvoiceSettings.builder()
                .company(company)
                .invoiceHeaderSubtitle(HEADER_SUBTITLE)
                .invoiceNotesUnpaid(NOTES_UNPAID)
                .invoiceNotesPaid(NOTES_PAID)
                .invoiceTerms(TERMS)
                .invoiceFooterCompanyLine(companyLine)
                .invoiceFooterTaxLine(taxLine)
                .invoiceFooterSignatureNote(FOOTER_SIGNATURE)
                .invoiceFooterSupportEmail(company.getCompanyEmail() == null ? "info@company.com" : company.getCompanyEmail())
                .invoiceFooterBillingEmail(company.getBillingEmail() == null ? "accounts@company.com" : company.getBillingEmail())
                .invoiceQrEnabled(false)
                .build();
    }
}
