package com.erp.dto.file;

public enum FileCategory {
    EMPLOYEE_PROFILE,
    INVENTORY_IMAGE,
    COMPANY_LOGO,
    INVOICE_PDF,
    PAYMENT_RECEIPT_PDF,
    GOODS_RECEIPT_PDF,
    LEAVE_SUPPORTING_DOCUMENT,
    CONTRACT_ATTACHMENT,
    PURCHASE_REQUISITION_DOCUMENT,
    PASSPORT_DOCUMENT,
    RESIDENCE_PERMIT_DOCUMENT
}

