spring:
  profiles:
    active: mysql

app:
  jwt:
    secret: "change-this-in-prod-32-bytes-minimum-secret-key-123456"
    issuer: "hrmodule"
    access-token-minutes: 60
    refresh-token-days: 7
  cors:
    allowed-origins: "http://localhost:5173,http://localhost:3001,http://localhost:3000,https://sunway-erp.vercel.app*,
      https://api.picominds.com"
server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: DEBUG
    org.springframework.data.jpa: DEBUG
    org.hibernate.SQL: INFO

springdoc:
  override-server-url: true

