CREATE TABLE IF NOT EXISTS `stock_variances` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `company_id` bigint NOT NULL,
    `item_id` bigint NOT NULL,
    `from_warehouse_id` bigint NOT NULL,
    `to_warehouse_id` bigint DEFAULT NULL,
    `variance_type` varchar(50) NOT NULL,
    `variance_status` varchar(30) NOT NULL,
    `adjustment_mode` varchar(20) NOT NULL,
    `quantity_before` int NOT NULL,
    `quantity_after` int DEFAULT NULL,
    `adjustment_quantity` int DEFAULT NULL,
    `transfer_quantity` int DEFAULT NULL,
    `reason` varchar(500) NOT NULL,
    `notes` text,
    `variance_date` date NOT NULL,
    `finance_transaction_id` bigint DEFAULT NULL,
    `created_by` bigint NOT NULL,
    `created_at` datetime(6) NOT NULL,
    `approved_by` bigint DEFAULT NULL,
    `approved_at` datetime(6) DEFAULT NULL,
    `rejected_by` bigint DEFAULT NULL,
    `rejected_at` datetime(6) DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_stock_variances_company_status` (`company_id`, `variance_status`),
    KEY `idx_stock_variances_item` (`item_id`),
    CONSTRAINT `fk_stock_variances_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
    CONSTRAINT `fk_stock_variances_item` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`),
    CONSTRAINT `fk_stock_variances_from_wh` FOREIGN KEY (`from_warehouse_id`) REFERENCES `warehouses` (`id`),
    CONSTRAINT `fk_stock_variances_to_wh` FOREIGN KEY (`to_warehouse_id`) REFERENCES `warehouses` (`id`),
    CONSTRAINT `fk_stock_variances_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
    CONSTRAINT `fk_stock_variances_approved_by` FOREIGN KEY (`approved_by`) REFERENCES `users` (`id`),
    CONSTRAINT `fk_stock_variances_rejected_by` FOREIGN KEY (`rejected_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
