-- Bulk-upload permission modules for HR / Finance / Inventory settings.
-- Admin-only grants (enforced in the UI + permission write endpoints).

ALTER TABLE `employee_permissions`
  MODIFY COLUMN `module` ENUM(
    'EMPLOYEE_PROFILE','CURRENT_JOB','SALARY','PAYROLL','LEAVES','LOANS','DEPENDENTS',
    'APPRAISAL','IMMIGRATION','HR_REPORTS','HR_SETTINGS','HR_DASHBOARD',
    'INVENTORY_CATEGORY','INVENTORY_WAREHOUSE','INVENTORY_STOCK','INVENTORY_ITEM',
    'INVENTORY_PURCHASE','INVENTORY_RECEIPT','INVENTORY_SALES','INVENTORY_DASHBOARD',
    'INVS_BULK_UPLOAD','INVENTORY_ITEM_BULK_UPLOAD','INVENTORY_VENDOR_BULK_UPLOAD',
    'FINANCE_COA','FINANCE_JOURNAL','FINANCE_LEDGER','FINANCE_INVOICE','FINANCE_PAYMENT',
    'FINANCE_BUDGET','FINANCE_RECONCILIATION','FINANCE_REPORTS','FINANCE_DASHBOARD',
    'FINS_BULK_UPLOAD',
    'HRS_ORG_STRUCTURE','HRS_DEPARTMENTS','HRS_JOB_CODES','HRS_ROLES','HRS_CONFIRMATIONS',
    'HRS_CONTRACT_RENEWALS','HRS_APPRAISAL_CONFIG','HRS_LEAVE_TYPES','HRS_LEAVE_APPROVALS',
    'HRS_LOAN_APPROVALS','HRS_POLICIES','HRS_SOCIAL','HRS_PERMISSIONS','HRS_BULK_UPLOAD',
    'HRR_WORKFORCE','HRR_PERFORMANCE','HRR_TIMESHEETS','HRR_ATTENDANCE_HISTORY',
    'HRR_LEAVE_HISTORY','HRR_LOAN_HISTORY','HRR_IMMIGRATION_EXPIRY','HRR_PAYROLL_SUMMARY',
    'HRR_EXIT_INTERVIEWS','HRR_ARCHIVE','HRR_HISTORY'
  ) NOT NULL;

ALTER TABLE `company_role_permissions`
  MODIFY COLUMN `module` ENUM(
    'EMPLOYEE_PROFILE','CURRENT_JOB','SALARY','PAYROLL','LEAVES','LOANS','DEPENDENTS',
    'APPRAISAL','IMMIGRATION','HR_REPORTS','HR_SETTINGS','HR_DASHBOARD',
    'INVENTORY_CATEGORY','INVENTORY_WAREHOUSE','INVENTORY_STOCK','INVENTORY_ITEM',
    'INVENTORY_PURCHASE','INVENTORY_RECEIPT','INVENTORY_SALES','INVENTORY_DASHBOARD',
    'INVS_BULK_UPLOAD','INVENTORY_ITEM_BULK_UPLOAD','INVENTORY_VENDOR_BULK_UPLOAD',
    'FINANCE_COA','FINANCE_JOURNAL','FINANCE_LEDGER','FINANCE_INVOICE','FINANCE_PAYMENT',
    'FINANCE_BUDGET','FINANCE_RECONCILIATION','FINANCE_REPORTS','FINANCE_DASHBOARD',
    'FINS_BULK_UPLOAD',
    'HRS_ORG_STRUCTURE','HRS_DEPARTMENTS','HRS_JOB_CODES','HRS_ROLES','HRS_CONFIRMATIONS',
    'HRS_CONTRACT_RENEWALS','HRS_APPRAISAL_CONFIG','HRS_LEAVE_TYPES','HRS_LEAVE_APPROVALS',
    'HRS_LOAN_APPROVALS','HRS_POLICIES','HRS_SOCIAL','HRS_PERMISSIONS','HRS_BULK_UPLOAD',
    'HRR_WORKFORCE','HRR_PERFORMANCE','HRR_TIMESHEETS','HRR_ATTENDANCE_HISTORY',
    'HRR_LEAVE_HISTORY','HRR_LOAN_HISTORY','HRR_IMMIGRATION_EXPIRY','HRR_PAYROLL_SUMMARY',
    'HRR_EXIT_INTERVIEWS','HRR_ARCHIVE','HRR_HISTORY'
  ) NOT NULL;

ALTER TABLE `enum_role_permissions`
  MODIFY COLUMN `module` ENUM(
    'EMPLOYEE_PROFILE','CURRENT_JOB','SALARY','PAYROLL','LEAVES','LOANS','DEPENDENTS',
    'APPRAISAL','IMMIGRATION','HR_REPORTS','HR_SETTINGS','HR_DASHBOARD',
    'INVENTORY_CATEGORY','INVENTORY_WAREHOUSE','INVENTORY_STOCK','INVENTORY_ITEM',
    'INVENTORY_PURCHASE','INVENTORY_RECEIPT','INVENTORY_SALES','INVENTORY_DASHBOARD',
    'INVS_BULK_UPLOAD','INVENTORY_ITEM_BULK_UPLOAD','INVENTORY_VENDOR_BULK_UPLOAD',
    'FINANCE_COA','FINANCE_JOURNAL','FINANCE_LEDGER','FINANCE_INVOICE','FINANCE_PAYMENT',
    'FINANCE_BUDGET','FINANCE_RECONCILIATION','FINANCE_REPORTS','FINANCE_DASHBOARD',
    'FINS_BULK_UPLOAD',
    'HRS_ORG_STRUCTURE','HRS_DEPARTMENTS','HRS_JOB_CODES','HRS_ROLES','HRS_CONFIRMATIONS',
    'HRS_CONTRACT_RENEWALS','HRS_APPRAISAL_CONFIG','HRS_LEAVE_TYPES','HRS_LEAVE_APPROVALS',
    'HRS_LOAN_APPROVALS','HRS_POLICIES','HRS_SOCIAL','HRS_PERMISSIONS','HRS_BULK_UPLOAD',
    'HRR_WORKFORCE','HRR_PERFORMANCE','HRR_TIMESHEETS','HRR_ATTENDANCE_HISTORY',
    'HRR_LEAVE_HISTORY','HRR_LOAN_HISTORY','HRR_IMMIGRATION_EXPIRY','HRR_PAYROLL_SUMMARY',
    'HRR_EXIT_INTERVIEWS','HRR_ARCHIVE','HRR_HISTORY'
  ) NOT NULL;
