-- Add PAYROLL to the permission module enum so payroll endpoints can be
-- governed by the same role/employee permission tables as the rest of HR.
-- Mirrors V20260616 (inventory modules); the full value list must be repeated
-- because MySQL MODIFY replaces the enum definition wholesale.

ALTER TABLE `employee_permissions`
  MODIFY COLUMN `module` enum(
    'APPRAISAL','CURRENT_JOB','DEPENDENTS','EMPLOYEE_PROFILE','HR_REPORTS','HR_SETTINGS',
    'IMMIGRATION','LEAVES','LOANS','SALARY','PAYROLL',
    'INVENTORY_CATEGORY','INVENTORY_WAREHOUSE','INVENTORY_STOCK','INVENTORY_ITEM',
    'INVENTORY_PURCHASE','INVENTORY_RECEIPT','INVENTORY_SALES'
  ) NOT NULL;

ALTER TABLE `company_role_permissions`
  MODIFY COLUMN `module` enum(
    'APPRAISAL','CURRENT_JOB','DEPENDENTS','EMPLOYEE_PROFILE','HR_REPORTS','HR_SETTINGS',
    'IMMIGRATION','LEAVES','LOANS','SALARY','PAYROLL',
    'INVENTORY_CATEGORY','INVENTORY_WAREHOUSE','INVENTORY_STOCK','INVENTORY_ITEM',
    'INVENTORY_PURCHASE','INVENTORY_RECEIPT','INVENTORY_SALES'
  ) NOT NULL;

ALTER TABLE `enum_role_permissions`
  MODIFY COLUMN `module` enum(
    'APPRAISAL','CURRENT_JOB','DEPENDENTS','EMPLOYEE_PROFILE','HR_REPORTS','HR_SETTINGS',
    'IMMIGRATION','LEAVES','LOANS','SALARY','PAYROLL',
    'INVENTORY_CATEGORY','INVENTORY_WAREHOUSE','INVENTORY_STOCK','INVENTORY_ITEM',
    'INVENTORY_PURCHASE','INVENTORY_RECEIPT','INVENTORY_SALES'
  ) NOT NULL;
