-- Extend permission module enum to support inventory modules (matches PermissionsTab INVENTORY_* keys).

ALTER TABLE `employee_permissions`
  MODIFY COLUMN `module` enum(
    'APPRAISAL','CURRENT_JOB','DEPENDENTS','EMPLOYEE_PROFILE','HR_REPORTS','HR_SETTINGS',
    'IMMIGRATION','LEAVES','LOANS','SALARY',
    'INVENTORY_CATEGORY','INVENTORY_WAREHOUSE','INVENTORY_STOCK','INVENTORY_ITEM',
    'INVENTORY_PURCHASE','INVENTORY_RECEIPT','INVENTORY_SALES'
  ) NOT NULL;

ALTER TABLE `company_role_permissions`
  MODIFY COLUMN `module` enum(
    'APPRAISAL','CURRENT_JOB','DEPENDENTS','EMPLOYEE_PROFILE','HR_REPORTS','HR_SETTINGS',
    'IMMIGRATION','LEAVES','LOANS','SALARY',
    'INVENTORY_CATEGORY','INVENTORY_WAREHOUSE','INVENTORY_STOCK','INVENTORY_ITEM',
    'INVENTORY_PURCHASE','INVENTORY_RECEIPT','INVENTORY_SALES'
  ) NOT NULL;

ALTER TABLE `enum_role_permissions`
  MODIFY COLUMN `module` enum(
    'APPRAISAL','CURRENT_JOB','DEPENDENTS','EMPLOYEE_PROFILE','HR_REPORTS','HR_SETTINGS',
    'IMMIGRATION','LEAVES','LOANS','SALARY',
    'INVENTORY_CATEGORY','INVENTORY_WAREHOUSE','INVENTORY_STOCK','INVENTORY_ITEM',
    'INVENTORY_PURCHASE','INVENTORY_RECEIPT','INVENTORY_SALES'
  ) NOT NULL;
