-- Add the per-area DASHBOARD modules (HR_DASHBOARD, INVENTORY_DASHBOARD,
-- FINANCE_DASHBOARD) to the permission module enum so each area's sidebar
-- dashboard becomes a grantable, view-only permission of its own.
-- Mirrors V20260616 (inventory) / V20260620 (payroll) / V20260621 (finance);
-- MySQL MODIFY replaces the enum definition wholesale, so the full value list
-- must be repeated.

ALTER TABLE `employee_permissions`
  MODIFY COLUMN `module` enum(
    'APPRAISAL','CURRENT_JOB','DEPENDENTS','EMPLOYEE_PROFILE','HR_REPORTS','HR_SETTINGS',
    'IMMIGRATION','LEAVES','LOANS','SALARY','PAYROLL','HR_DASHBOARD',
    'INVENTORY_CATEGORY','INVENTORY_WAREHOUSE','INVENTORY_STOCK','INVENTORY_ITEM',
    'INVENTORY_PURCHASE','INVENTORY_RECEIPT','INVENTORY_SALES','INVENTORY_DASHBOARD',
    'FINANCE_COA','FINANCE_JOURNAL','FINANCE_LEDGER','FINANCE_INVOICE',
    'FINANCE_PAYMENT','FINANCE_BUDGET','FINANCE_RECONCILIATION','FINANCE_REPORTS','FINANCE_DASHBOARD'
  ) NOT NULL;

ALTER TABLE `company_role_permissions`
  MODIFY COLUMN `module` enum(
    'APPRAISAL','CURRENT_JOB','DEPENDENTS','EMPLOYEE_PROFILE','HR_REPORTS','HR_SETTINGS',
    'IMMIGRATION','LEAVES','LOANS','SALARY','PAYROLL','HR_DASHBOARD',
    'INVENTORY_CATEGORY','INVENTORY_WAREHOUSE','INVENTORY_STOCK','INVENTORY_ITEM',
    'INVENTORY_PURCHASE','INVENTORY_RECEIPT','INVENTORY_SALES','INVENTORY_DASHBOARD',
    'FINANCE_COA','FINANCE_JOURNAL','FINANCE_LEDGER','FINANCE_INVOICE',
    'FINANCE_PAYMENT','FINANCE_BUDGET','FINANCE_RECONCILIATION','FINANCE_REPORTS','FINANCE_DASHBOARD'
  ) NOT NULL;

ALTER TABLE `enum_role_permissions`
  MODIFY COLUMN `module` enum(
    'APPRAISAL','CURRENT_JOB','DEPENDENTS','EMPLOYEE_PROFILE','HR_REPORTS','HR_SETTINGS',
    'IMMIGRATION','LEAVES','LOANS','SALARY','PAYROLL','HR_DASHBOARD',
    'INVENTORY_CATEGORY','INVENTORY_WAREHOUSE','INVENTORY_STOCK','INVENTORY_ITEM',
    'INVENTORY_PURCHASE','INVENTORY_RECEIPT','INVENTORY_SALES','INVENTORY_DASHBOARD',
    'FINANCE_COA','FINANCE_JOURNAL','FINANCE_LEDGER','FINANCE_INVOICE',
    'FINANCE_PAYMENT','FINANCE_BUDGET','FINANCE_RECONCILIATION','FINANCE_REPORTS','FINANCE_DASHBOARD'
  ) NOT NULL;
