-- Add the FINANCE_* modules to the permission module enum so finance endpoints
-- can be governed by the same role/employee permission tables as HR & inventory.
-- Mirrors V20260616 (inventory) / V20260620 (payroll); MySQL MODIFY replaces the
-- enum definition wholesale, so the full value list must be repeated.

ALTER TABLE `employee_permissions`
  MODIFY COLUMN `module` enum(
    'APPRAISAL','CURRENT_JOB','DEPENDENTS','EMPLOYEE_PROFILE','HR_REPORTS','HR_SETTINGS',
    'IMMIGRATION','LEAVES','LOANS','SALARY','PAYROLL',
    'INVENTORY_CATEGORY','INVENTORY_WAREHOUSE','INVENTORY_STOCK','INVENTORY_ITEM',
    'INVENTORY_PURCHASE','INVENTORY_RECEIPT','INVENTORY_SALES',
    'FINANCE_COA','FINANCE_JOURNAL','FINANCE_LEDGER','FINANCE_INVOICE',
    'FINANCE_PAYMENT','FINANCE_BUDGET','FINANCE_RECONCILIATION','FINANCE_REPORTS'
  ) NOT NULL;

ALTER TABLE `company_role_permissions`
  MODIFY COLUMN `module` enum(
    'APPRAISAL','CURRENT_JOB','DEPENDENTS','EMPLOYEE_PROFILE','HR_REPORTS','HR_SETTINGS',
    'IMMIGRATION','LEAVES','LOANS','SALARY','PAYROLL',
    'INVENTORY_CATEGORY','INVENTORY_WAREHOUSE','INVENTORY_STOCK','INVENTORY_ITEM',
    'INVENTORY_PURCHASE','INVENTORY_RECEIPT','INVENTORY_SALES',
    'FINANCE_COA','FINANCE_JOURNAL','FINANCE_LEDGER','FINANCE_INVOICE',
    'FINANCE_PAYMENT','FINANCE_BUDGET','FINANCE_RECONCILIATION','FINANCE_REPORTS'
  ) NOT NULL;

ALTER TABLE `enum_role_permissions`
  MODIFY COLUMN `module` enum(
    'APPRAISAL','CURRENT_JOB','DEPENDENTS','EMPLOYEE_PROFILE','HR_REPORTS','HR_SETTINGS',
    'IMMIGRATION','LEAVES','LOANS','SALARY','PAYROLL',
    'INVENTORY_CATEGORY','INVENTORY_WAREHOUSE','INVENTORY_STOCK','INVENTORY_ITEM',
    'INVENTORY_PURCHASE','INVENTORY_RECEIPT','INVENTORY_SALES',
    'FINANCE_COA','FINANCE_JOURNAL','FINANCE_LEDGER','FINANCE_INVOICE',
    'FINANCE_PAYMENT','FINANCE_BUDGET','FINANCE_RECONCILIATION','FINANCE_REPORTS'
  ) NOT NULL;
